### ISSUE TITLE
AWS Lambda giving previous value 

### ISSUE THREAD

**Issue by aneeshjose** [dwyl/learn-aws-lambda#105]
I am using AWS lambda and API gateway for my project. I am doing a converter.
I have created the lambda function and API. I am stuck with the problem below
step 1: I have entered the value 1 in get and the page gives the answer 'undefined'.
step 2:I have entered the value 2 in get and the page produce an answer that is meant for value 1.

Please help me fast .
Thank you in advance and sorry for bad English.

**Comment by nelsonic** [comment]
"Please help me fast" ... 

@aneeshjose you have given insufficient information for us to _begin_ to help you with this.
Also, it's _unrelated_ to the contents of this repository ... i.e. not strictly relevant.
