### ISSUE TITLE
Add an example of a Lambda function triggered by a DynamoDB event

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/learn-aws-lambda#13]

**Comment by nikhilaravi** [comment]
<img width="1158" alt="screen shot 2016-01-25 at 15 22 55" src="https://cloud.githubusercontent.com/assets/5912647/12557398/7114929c-c382-11e5-9c48-5c2bf15649ac.png">

**Comment by nikhilaravi** [comment]
<img width="1255" alt="screen shot 2016-01-25 at 17 41 42" src="https://cloud.githubusercontent.com/assets/5912647/12559366/b08d36e0-c38c-11e5-944a-b9da7596ddee.png">

**Comment by nikhilaravi** [comment]
<img width="1255" alt="screen shot 2016-01-25 at 17 42 22" src="https://cloud.githubusercontent.com/assets/5912647/12559413/edeb637c-c38c-11e5-959e-4fa6388f93dc.png">

**Comment by nikhilaravi** [comment]
<img width="1161" alt="screen shot 2016-01-25 at 15 46 17" src="https://cloud.githubusercontent.com/assets/5912647/12557478/e3e383be-c382-11e5-9456-81d7504a7e8e.png">

**Comment by nikhilaravi** [comment]
<img w
<img width="1255" alt="screen shot 2016-01-25 at 17 43 37" src="https://cloud.githubusercontent.com/assets/5912647/12559453/0ff42378-c38d-11e5-9546-698c39429199.png">

**Comment by nikhilaravi** [comment]
<img width="957" alt="screen shot 2016-01-25 at 15 49 32" src="https://cloud.githubusercontent.com/assets/5912647/12557522/1cb82a5a-c383-11e5-9771-50036f46940e.png">

**Comment by nikhilaravi** [comment]
<img width="1010" alt="screen shot 2016-01-25 at 15 53 21" src="https://cloud.githubusercontent.com/assets/5912647/12557588/75019368-c383-11e5-9824-f6c6f721f03d.png">

**Comment by nikhilaravi** [comment]
<img width="1130" alt="screen shot 2016-01-25 at 15 55 13" src="https://cloud.githubusercontent.com/assets/5912647/12557604/8f24704e-c383-11e5-90f5-2dc15723c2c5.png">

**Comment by nikhilaravi** [comment]
<img width="933" alt="screen shot 2016-01-25 at 16 02 28" src="https://cloud.githubusercontent.com/assets/5912647/12557637/ba8ae330-c383-11e5-8fde-f6912a681f51.png">

**Comment by nikhilaravi** [comment]
<img width="1252" alt="screen shot 2016-01-25 at 17 51 05" src="https://cloud.githubusercontent.com/assets/5912647/12563887/4cd15e34-c3a4-11e5-8b65-c16a909c3637.png">

**Comment by nikhilaravi** [comment]
<img width="1256" alt="screen shot 2016-01-25 at 17 51 22" src="https://cloud.githubusercontent.com/assets/5912647/12563894/56dd9852-c3a4-11e5-986a-be381262c536.png">

**Comment by nikhilaravi** [comment]
<img width="1255" alt="screen shot 2016-01-25 at 17 52 25" src="https://cloud.githubusercontent.com/assets/5912647/12563914/62fb5b38-c3a4-11e5-9830-f87e65a4468b.png">

**Comment by nikhilaravi** [comment]
<img width="937" alt="screen shot 2016-01-25 at 16 09 29" src="https://cloud.githubusercontent.com/assets/5912647/12557777/55046eea-c384-11e5-9abe-db37615ba2d4.png">

**Comment by nikhilaravi** [comment]
<img width="1136" alt="screen shot 2016-01-25 at 16 14 41" src="https://cloud.githubusercontent.com/assets/5912647/12557807/7320f4a2-c384-11e5-9fcd-b399285fad92.png">

**Comment by nikhilaravi** [comment]
<img width="944" alt="screen shot 2016-01-25 at 16 15 54" src="https://cloud.githubusercontent.com/assets/5912647/12557836/996c7b22-c384-11e5-88d8-c7b16c368f25.png">

**Comment by nelsonic** [comment]
Can we close this?
or are you going to add a more _detailed_ example?

**Comment by nikhilaravi** [comment]
@nelsonic For the moment I'm not planning on adding anything more detailed so I'll close it now!
