### ISSUE TITLE
Write documentation on how to implement versioning and aliases for Lambda functions

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/learn-aws-lambda#17]
This could be useful for us when we're working with different variations of our Lambda function in the development workflow. 
http://docs.aws.amazon.com/lambda/latest/dg/versioning-aliases.html

**Comment by nelsonic** [comment]
This is _essential_ thanks for looking into it! :+1:

**Comment by nikhilaravi** [comment]
Info added in #34
