### ISSUE TITLE
Write an example of triggering a Lambda function from an SNS notification

### ISSUE THREAD

**Issue by nikhilaravi** [dwyl/learn-aws-lambda#18]

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 10 57 59" src="https://cloud.githubusercontent.com/assets/5912647/12579896/4652ea94-c423-11e5-8a15-e31c3d586405.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 10 58 23" src="https://cloud.githubusercontent.com/assets/5912647/12579906/54c371de-c423-11e5-8982-9668384cf90a.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 11 10 29" src="https://cloud.githubusercontent.com/assets/5912647/12579931/7d7ce47a-c423-11e5-973c-e0e03e1cf990.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 11 18 51" src="https://cloud.githubusercontent.com/assets/5912647/12579947/97b24344-c423-11e5-93b8-f658b8c9db5b.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 11 23 46" src="https://cloud.githubusercontent.com/assets/5912647/12579960/a5dd5238-c423-11e5-90df-40b3c88f7e05.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 11 25 36" src="https://cloud.githubusercontent.com/assets/5912647/12579968/c3410dec-c423-11e5-9189-3dd68fe7060c.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 11 28 02" src="https://cloud.githubusercontent.com/assets/5912647/12579987/db74a798-c423-11e5-94e4-86965a9c8d82.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 11 29 34" src="https://cloud.githubusercontent.com/assets/5912647/12579999/ff48d928-c423-11e5-9b02-45b7ecc7b1d4.png">

**Comment by nikhilaravi** [comment]
<img width="1280" alt="screen shot 2016-01-26 at 11 29 26" src="https://cloud.githubusercontent.com/assets/5912647/12580016/18dc1f76-c424-11e5-8d27-ecd4f1ae68e0.png">

**Comment by nelsonic** [comment]
@nikhilaravi this was in your last PR and I've followed your notes and they are _good_. :+1: 
Feel free to close this issue if you aren't going to add anything else to the example. :wink:

**Comment by nikhilaravi** [comment]
@nelsonic sure will do! Need to remember to close issues from my PRs!!
