### ISSUE TITLE
how to do continuous integration with lambda functions

### ISSUE THREAD

**Issue by benjaminlees** [dwyl/learn-aws-lambda#19]
@nelsonic I would be happy to work with you on a follow up tutorial to cover this issue. there is no good documentation on it.

**Comment by nelsonic** [comment]
Yes! :boom:

**Comment by nikhilaravi** [comment]
@benjaminlees :+1: keen to help with this too! Want to get better at testing!

**Comment by nikhilaravi** [comment]
@benjaminlees what do you use for CI? I found this tutorial with Jenkins https://aws.amazon.com/blogs/compute/continuous-integration-deployment-for-aws-lambda-functions-with-jenkins-and-grunt-part-2/

**Comment by nelsonic** [comment]
@nikhilaravi I think @benjaminlees & Co are using https://circleci.com/features/
but we will be using https://codeship.com/features for our builds. :+1:

**Comment by nelsonic** [comment]
See: https://codeship.com/documentation/continuous-deployment/deployment-to-aws-lambda/

**Comment by nikhilaravi** [comment]
:+1: nice! :star:

**Comment by nikhilaravi** [comment]
<img width="1472" alt="screen shot 2016-01-27 at 15 01 20" src="https://cloud.githubusercontent.com/assets/5912647/12617272/de1cc1b8-c506-11e5-98e4-1dc8692450e0.png">

**Comment by nikhilaravi** [comment]
<img width="1469" alt="screen shot 2016-01-27 at 14 47 31" src="https://cloud.githubusercontent.com/assets/5912647/12616879/1815056c-c505-11e5-90b9-81ae434c1ed3.png">

**Comment by nikhilaravi** [comment]
<img width="1471" alt="screen shot 2016-01-27 at 14 51 57" src="https://cloud.githubusercontent.com/assets/5912647/12617062/f75caa9a-c505-11e5-9ff9-551df7aa8f38.png">

**Comment by nikhilaravi** [comment]
<img width="1475" alt="screen shot 2016-01-27 at 14 54 01" src="https://cloud.githubusercontent.com/assets/5912647/12617077/07b7bdee-c506-11e5-941f-a35ae14e2bdc.png">

**Comment by nikhilaravi** [comment]
<img width="1474" alt="screen shot 2016-01-27 at 14 56 43" src="https://cloud.githubusercontent.com/assets/5912647/12617139/3a2d249e-c506-11e5-898a-b3f9307e0da2.png">

**Comment by nikhilaravi** [comment]
<img width="1474" alt="screen shot 2016-01-27 at 15 28 28" src="https://cloud.githubusercontent.com/assets/5912647/12618166/a88dee74-c50a-11e5-8668-cec9a9430782.png">

**Comment by nikhilaravi** [comment]
<img width="1471" alt="screen shot 2016-01-27 at 15 50 10" src="https://cloud.githubusercontent.com/assets/5912647/12618996/21f8c876-c50e-11e5-9c5b-668a5c56a3df.png">

**Comment by nikhilaravi** [comment]
<img width="1470" alt="screen shot 2016-01-27 at 15 54 55" src="https://cloud.githubusercontent.com/assets/5912647/12619073/63294abe-c50e-11e5-9f91-2452078968ef.png">

**Comment by nikhilaravi** [comment]
<img width="1266" alt="screen shot 2016-01-27 at 13 43 58" src="https://cloud.githubusercontent.com/assets/5912647/12619098/83e071a6-c50e-11e5-8d28-45c8afc19f2e.png">

**Comment by nikhilaravi** [comment]
<img width="1473" alt="screen shot 2016-01-27 at 15 58 02" src="https://cloud.githubusercontent.com/assets/5912647/12619166/d12aeb30-c50e-11e5-8d36-c3e1f60baef3.png">

**Comment by nikhilaravi** [comment]
<img width="1473" alt="screen shot 2016-01-27 at 15 59 16" src="https://cloud.githubusercontent.com/assets/5912647/12619195/f92df8b6-c50e-11e5-8c82-fc9c55021a22.png">

**Comment by nikhilaravi** [comment]
<img width="1472" alt="screen shot 2016-01-27 at 16 00 27" src="https://cloud.githubusercontent.com/assets/5912647/12619261/2ba08fca-c50f-11e5-9c2c-db510e977e65.png">

**Comment by nikhilaravi** [comment]
<img width="1474" alt="screen shot 2016-01-27 at 16 03 47" src="https://cloud.githubusercontent.com/assets/5912647/12619374/9df7bbb6-c50f-11e5-96de-2b7e1aee366f.png">

**Comment by nikhilaravi** [comment]
<img width="1472" alt="screen shot 2016-01-27 at 16 04 57" src="https://cloud.githubusercontent.com/assets/5912647/12619412/cb2df10e-c50f-11e5-8af3-d53c11d4953b.png">
