### ISSUE TITLE
Serverless (Framework) 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-lambda#2]
Should we investigate using JAWS?
https://github.com/jaws-stack/JAWS
Possibly even write a sample application using the stack?

**Comment by nelsonic** [comment]
JAWS >> Serverless 
https://github.com/serverless/serverless
http://docs.serverless.com/v0.1.0/docs

But people should only _consider_ using serverless once they have deployed a _simple_ Lambda script.

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 14 14 40](https://cloud.githubusercontent.com/assets/12450298/12822470/2854a2be-cb60-11e5-9822-11913fdd98e1.png)

**Comment by jackcarlisle** [comment]
<img width="1649" alt="screen shot 2016-02-04 at 14 29 04" src="https://cloud.githubusercontent.com/assets/12450298/12822479/2d889d44-cb60-11e5-8c89-9420378d6be6.png">

**Comment by jackcarlisle** [comment]
<img width="1650" alt="screen shot 2016-02-04 at 14 30 58" src="https://cloud.githubusercontent.com/assets/12450298/12822483/31bfc428-cb60-11e5-81f0-2990ec32ca41.png">

**Comment by jackcarlisle** [comment]
<img width="1651" alt="screen shot 2016-02-04 at 14 34 41" src="https://cloud.githubusercontent.com/assets/12450298/12822486/35574a98-cb60-11e5-8cd7-2e2f06ab5c41.png">

**Comment by jackcarlisle** [comment]
<img width="837" alt="screen shot 2016-02-04 at 14 34 50" src="https://cloud.githubusercontent.com/assets/12450298/12822489/39388622-cb60-11e5-900d-bda80d95cd5f.png">

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 14 46 09](https://cloud.githubusercontent.com/assets/12450298/12822493/3c00d544-cb60-11e5-9f32-543572f247f0.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 14 52 45](https://cloud.githubusercontent.com/assets/12450298/12822495/3ea624c0-cb60-11e5-87e5-4335faa9320a.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 14 52 59](https://cloud.githubusercontent.com/assets/12450298/12822502/43a7e9c2-cb60-11e5-8bd6-8fa5a0cf963b.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 14 54 29](https://cloud.githubusercontent.com/assets/12450298/12822506/48157dc6-cb60-11e5-9fcf-5206e2c351b7.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 14 59 35](https://cloud.githubusercontent.com/assets/12450298/12822510/4c8b6e38-cb60-11e5-80fe-2bc093f7f955.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 15 04 36](https://cloud.githubusercontent.com/assets/12450298/12822513/4f450b5c-cb60-11e5-990e-a5d175233442.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 15 42 22](https://cloud.githubusercontent.com/assets/12450298/12822517/51ffd138-cb60-11e5-9f97-41442febce66.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 15 43 03](https://cloud.githubusercontent.com/assets/12450298/12822528/5bd60a7e-cb60-11e5-9f55-460af2b6132c.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 15 58 19](https://cloud.githubusercontent.com/assets/12450298/12822531/5f22124a-cb60-11e5-8297-868c0cd250d2.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 15 58 59](https://cloud.githubusercontent.com/assets/12450298/12822535/624c67fe-cb60-11e5-8120-9f74d933994d.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 15 59 53](https://cloud.githubusercontent.com/assets/12450298/12822538/67e30e66-cb60-11e5-83e5-7e42b4fcc8c0.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 16 00 08](https://cloud.githubusercontent.com/assets/12450298/12822544/6ccb1ca2-cb60-11e5-8d1c-97e8e8224717.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-04 at 16 00 42](https://cloud.githubusercontent.com/assets/12450298/12822547/70f21056-cb60-11e5-90c8-e2a3fd4aa457.png)

**Comment by nelsonic** [comment]
@jackcarlisle can you share a _link_ to your findings so we can close this issue? 👍

**Comment by jackcarlisle** [comment]
[Serverless Tutorial](https://github.com/dwyl/learn-aws-lambda/blob/master/README.md#the-serverless-framework-previously-known-as-jaws)
