### ISSUE TITLE
Add Example Script to Upload a Lambda Function to S3 and Enable it!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-lambda#23]
This one is a bit more involved than our other examples, feel free to _borrow_ code from other projects (_but give credit with a link/comment_). :+1:

**Comment by jackcarlisle** [comment]
@nelsonic I'd be quite keen to look into this

**Comment by nelsonic** [comment]
@jackcarlisle please go for it if you're at a natural break in your GraphQL learnings...

**Comment by jackcarlisle** [comment]
<img width="1648" alt="screen shot 2016-01-28 at 14 19 32" src="https://cloud.githubusercontent.com/assets/12450298/12646827/32f97802-c5ca-11e5-84a8-b49e2cd0e929.png">

**Comment by jackcarlisle** [comment]
<img width="1677" alt="screen shot 2016-01-28 at 14 21 24" src="https://cloud.githubusercontent.com/assets/12450298/12646889/8f342590-c5ca-11e5-8e2f-e2cb2bccf04d.png">

**Comment by jackcarlisle** [comment]
<img width="1475" alt="screen shot 2016-01-28 at 14 36 22" src="https://cloud.githubusercontent.com/assets/12450298/12647320/7f9fdd52-c5cc-11e5-98d0-dfd68b6a8caf.png">

**Comment by jackcarlisle** [comment]
<img width="1464" alt="screen shot 2016-01-28 at 15 27 08" src="https://cloud.githubusercontent.com/assets/12450298/12648830/b1af1d4c-c5d3-11e5-91af-0d32691b7764.png">

**Comment by jackcarlisle** [comment]
<img width="1660" alt="screen shot 2016-01-28 at 15 40 40" src="https://cloud.githubusercontent.com/assets/12450298/12649316/06ac3a80-c5d6-11e5-8b05-d624d507a12e.png">

**Comment by jackcarlisle** [comment]
<img width="1647" alt="screen shot 2016-01-28 at 15 41 40" src="https://cloud.githubusercontent.com/assets/12450298/12649326/11a19a3e-c5d6-11e5-82e3-5136640fdeb4.png">

**Comment by jackcarlisle** [comment]
<img width="1417" alt="screen shot 2016-01-28 at 15 41 51" src="https://cloud.githubusercontent.com/assets/12450298/12649339/1c916cb2-c5d6-11e5-8109-34f51f860d5a.png">

**Comment by jackcarlisle** [comment]
<img width="1518" alt="screen shot 2016-01-28 at 15 42 08" src="https://cloud.githubusercontent.com/assets/12450298/12649344/214dc3a4-c5d6-11e5-8a8f-81b20ed9eeac.png">

**Comment by jackcarlisle** [comment]
<img width="1660" alt="screen shot 2016-01-28 at 15 51 02" src="https://cloud.githubusercontent.com/assets/12450298/12649566/095d28ba-c5d7-11e5-812d-97ea278cb285.png">

**Comment by jackcarlisle** [comment]
<img width="1647" alt="screen shot 2016-01-28 at 15 51 54" src="https://cloud.githubusercontent.com/assets/12450298/12649574/0f1dbcd8-c5d7-11e5-864e-d9e04b80882f.png">

**Comment by jackcarlisle** [comment]
<img width="1660" alt="screen shot 2016-01-28 at 16 00 43" src="https://cloud.githubusercontent.com/assets/12450298/12649893/73b3e590-c5d8-11e5-9cec-88bee1ac5c4d.png">

**Comment by jackcarlisle** [comment]
<img width="1454" alt="screen shot 2016-01-28 at 16 03 26" src="https://cloud.githubusercontent.com/assets/12450298/12650158/9c0df796-c5d9-11e5-91da-dc4f45d22c98.png">

**Comment by jackcarlisle** [comment]
<img width="1680" alt="screen shot 2016-01-28 at 16 24 07" src="https://cloud.githubusercontent.com/assets/12450298/12650714/bcb0664e-c5db-11e5-9d08-a2bf2f2c32ff.png">

**Comment by jackcarlisle** [comment]
<img width="1662" alt="screen shot 2016-01-28 at 16 24 29" src="https://cloud.githubusercontent.com/assets/12450298/12650757/ee4b886e-c5db-11e5-8505-08b3b4bc0958.png">
