### ISSUE TITLE
Migrate Test Example from Tape to Lab

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-lambda#29]
Hi @nikhilaravi,
the [_example_ tests](https://github.com/dwyl/learn-aws-lambda/blob/b964c8de00ce3f0c766ba362d5c1c4b0f8d8737a/lambda-testing/tests/index.js) you have written are _good_ however we've been informed that the client are using `Lab` for testing so we will need to update them...

**Comment by nelsonic** [comment]
@nikhilaravi can I do the conversion from Tape to Lab?
(_note: I personally prefer Tape every day of the week..._)

**Comment by nikhilaravi** [comment]
@nelsonic sure that's fine! I was informed of this too! I'll also have a look at how their tests are written in terms of mocking.
