### ISSUE TITLE
Add detail to AWS API Gateway Section

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-lambda#33]
This is quite good: https://auth0.com/docs/integrations/aws-api-gateway/part-1
part two gets a bit complex using the Auth0 API but part 1 is a good intro to setting up an API with GET/POST which uses a Lambda function to update/retrieve records from DynamoDB.

**Comment by jackcarlisle** [comment]
@nelsonic I'd quite like to look into this!

**Comment by nelsonic** [comment]
@jackcarlisle go for it. :+1:

**Comment by jackcarlisle** [comment]
<img width="1249" alt="screen shot 2016-02-01 at 10 01 21" src="https://cloud.githubusercontent.com/assets/12450298/12714146/cbf87b4a-c8ca-11e5-8e13-feca431afaf9.png">

**Comment by jackcarlisle** [comment]
<img width="1216" alt="screen shot 2016-02-01 at 10 07 59" src="https://cloud.githubusercontent.com/assets/12450298/12714300/c9a4e152-c8cb-11e5-8c35-370393cef70e.png">

**Comment by jackcarlisle** [comment]
<img width="1228" alt="screen shot 2016-02-01 at 10 16 09" src="https://cloud.githubusercontent.com/assets/12450298/12714466/db3a51d0-c8cc-11e5-882f-a3b09df203a4.png">

**Comment by jackcarlisle** [comment]
<img width="1271" alt="screen shot 2016-02-01 at 10 19 52" src="https://cloud.githubusercontent.com/assets/12450298/12714552/5fe19b1e-c8cd-11e5-919a-780c3bb06316.png">

**Comment by jackcarlisle** [comment]
<img width="1271" alt="screen shot 2016-02-01 at 10 21 35" src="https://cloud.githubusercontent.com/assets/12450298/12714608/9da7b6ea-c8cd-11e5-8b5c-f09f94d3e66a.png">

**Comment by jackcarlisle** [comment]
<img width="1260" alt="screen shot 2016-02-01 at 10 31 57" src="https://cloud.githubusercontent.com/assets/12450298/12714889/11c25804-c8cf-11e5-8b32-e01f9673b8cf.png">

**Comment by jackcarlisle** [comment]
<img width="1260" alt="screen shot 2016-02-01 at 10 33 46" src="https://cloud.githubusercontent.com/assets/12450298/12714963/651140f6-c8cf-11e5-87f5-f547605f757a.png">

**Comment by jackcarlisle** [comment]
<img width="1256" alt="screen shot 2016-02-01 at 10 34 20" src="https://cloud.githubusercontent.com/assets/12450298/12714986/8de42822-c8cf-11e5-9fc8-9aad5ed4b799.png">

**Comment by jackcarlisle** [comment]
<img width="1251" alt="screen shot 2016-02-01 at 10 36 53" src="https://cloud.githubusercontent.com/assets/12450298/12715013/bcb3bc1c-c8cf-11e5-8fce-37f32546d0b5.png">

**Comment by jackcarlisle** [comment]
<img width="1049" alt="screen shot 2016-02-01 at 10 38 41" src="https://cloud.githubusercontent.com/assets/12450298/12715051/feeb0bee-c8cf-11e5-9157-b61595ea376d.png">

**Comment by jackcarlisle** [comment]
<img width="1041" alt="screen shot 2016-02-01 at 10 40 15" src="https://cloud.githubusercontent.com/assets/12450298/12715091/385b678e-c8d0-11e5-8006-1d65487b933e.png">

**Comment by jackcarlisle** [comment]
<img width="1253" alt="screen shot 2016-02-01 at 10 42 32" src="https://cloud.githubusercontent.com/assets/12450298/12715150/857ad6e4-c8d0-11e5-9688-c6237746e742.png">

**Comment by jackcarlisle** [comment]
<img width="1269" alt="screen shot 2016-02-01 at 11 48 34" src="https://cloud.githubusercontent.com/assets/12450298/12716616/ceb37a6a-c8d9-11e5-80be-54ebf8b9754d.png">

**Comment by jackcarlisle** [comment]
<img width="982" alt="screen shot 2016-02-01 at 12 00 32" src="https://cloud.githubusercontent.com/assets/12450298/12716846/6d4dcd82-c8db-11e5-9b01-3dccc12d8fa5.png">

**Comment by jackcarlisle** [comment]
<img width="1266" alt="screen shot 2016-02-01 at 12 22 17" src="https://cloud.githubusercontent.com/assets/12450298/12717241/7e1805bc-c8de-11e5-9c0c-9974a961cef7.png">

**Comment by jackcarlisle** [comment]
<img width="1264" alt="screen shot 2016-02-02 at 09 09 03" src="https://cloud.githubusercontent.com/assets/12450298/12744540/be1404a0-c98c-11e5-8a7b-a0dfb74bc6f1.png">

**Comment by jackcarlisle** [comment]
<img width="1270" alt="screen shot 2016-02-02 at 09 16 00" src="https://cloud.githubusercontent.com/assets/12450298/12744749/cd30dd9a-c98d-11e5-97ce-217fe7adf74f.png">

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-05 at 14 30 28](https://cloud.githubusercontent.com/assets/12450298/12849024/2d7ae61c-cc15-11e5-8e92-1cefb9cc7bee.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-05 at 14 27 36](https://cloud.githubusercontent.com/assets/12450298/12849056/5e7c7082-cc15-11e5-87cc-51d921af1bd7.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-05 at 14 40 20](https://cloud.githubusercontent.com/assets/12450298/12849342/1d95f8ca-cc17-11e5-894b-3896f83d3f2f.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-05 at 14 41 29](https://cloud.githubusercontent.com/assets/12450298/12849531/f5d2f0ee-cc17-11e5-8162-cde17cdab2dc.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-05 at 14 54 23](https://cloud.githubusercontent.com/assets/12450298/12849623/87651974-cc18-11e5-8e88-ebf4f2b3c39d.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-05 at 14 54 50](https://cloud.githubusercontent.com/assets/12450298/12849673/cf1cf82c-cc18-11e5-8c8c-edac7bc0d39d.png)

**Comment by jackcarlisle** [comment]
![screen shot 2016-02-05 at 15 01 11](https://cloud.githubusercontent.com/assets/12450298/12849902/ebfa3602-cc19-11e5-92f6-ffa21320fd20.png)

**Comment by jackcarlisle** [comment]
[README Tutorial Link](https://github.com/dwyl/learn-aws-lambda/blob/8fa666fd71481e64bb46ecf363f3fdbaa5677d95/README.md#create-an-api-with-getpost-methods-that-uses-lambda-functions-to-retrieveupdate-records-from-a-dynamodb-table-1)
