### ISSUE TITLE
Hello World Example?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-lambda#5]
What is the AWS Lambda `Hello World` ?

**Comment by jackcarlisle** [comment]
I'll start to put together a Hello World example

**Comment by jackcarlisle** [comment]
<img width="935" alt="screen shot 2016-01-23 at 11 01 45" src="https://cloud.githubusercontent.com/assets/12450298/12529878/e9c55334-c1c0-11e5-9a90-56b296d5b3fb.png">

**Comment by jackcarlisle** [comment]
<img width="921" alt="screen shot 2016-01-23 at 11 18 14" src="https://cloud.githubusercontent.com/assets/12450298/12529907/061d8e28-c1c3-11e5-9509-24cd1548417d.png">

**Comment by jackcarlisle** [comment]
<img width="917" alt="screen shot 2016-01-23 at 11 31 06" src="https://cloud.githubusercontent.com/assets/12450298/12529957/dace98fa-c1c4-11e5-9df3-a6709cddcdab.png">

**Comment by jackcarlisle** [comment]
<img width="1662" alt="screen shot 2016-01-23 at 11 58 04" src="https://cloud.githubusercontent.com/assets/12450298/12530052/a8e296b2-c1c8-11e5-9ef1-4d19367a4980.png">

**Comment by jackcarlisle** [comment]
<img width="848" alt="screen shot 2016-01-23 at 12 05 22" src="https://cloud.githubusercontent.com/assets/12450298/12530077/e1a703d8-c1c9-11e5-97f8-00cdf390bcdc.png">

**Comment by jackcarlisle** [comment]
<img width="1663" alt="screen shot 2016-01-23 at 12 21 35" src="https://cloud.githubusercontent.com/assets/12450298/12530135/1a62941a-c1cc-11e5-87d8-d8077bd599ce.png">

**Comment by jackcarlisle** [comment]
@nelsonic I've finished the Hello World example but I don't have access to the repo to make a pull request

**Comment by jackcarlisle** [comment]
@nelsonic Are my screenshots ok in terms of sensitive data? I wasn't sure if there was anything I should be obscuring for example request IDs or my ARN?

**Comment by nelsonic** [comment]
@jackcarlisle request ids are not sensitive. only the keys. your screenshots are fine. :+1:
