### ISSUE TITLE
How to Invoke an AWS.Lambda function from within another lambda function?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-aws-lambda#68]
@hyprstack asked the question on StackOverflow: http://stackoverflow.com/questions/35754766/nodejs-invoke-an-aws-lambda-function-from-within-another-lambda-function
its our job to reply! :rainbow:

**Comment by nelsonic** [comment]
![lambda invoke](https://cloud.githubusercontent.com/assets/194400/13526240/ac778494-e1fe-11e5-8462-816a0b85ed3d.jpg)

**Comment by nelsonic** [comment]
![lambda-role-for-intra-lambda-execution](https://cloud.githubusercontent.com/assets/194400/13526641/15a146c4-e201-11e5-88c1-c70c9eda2bfb.png)

![lambda invoke-lambda_a-execution-result](https://cloud.githubusercontent.com/assets/194400/13526744/ec22a062-e201-11e5-8c7b-6bea3b437bd4.png)

**Comment by hyprstack** [comment]
Awesome! Thanks guys! AWS configs/permissions at their best....once again!

**Comment by nelsonic** [comment]
@hyprstack see: http://stackoverflow.com/questions/35754766/nodejs-invoke-an-aws-lambda-function-from-within-another-lambda-function/35795883#35795883 
Let us know if you need any elaboration on the answer. :+1:

**Comment by nelsonic** [comment]
Closing. :white_check_mark:
