### ISSUE TITLE
.zip file upload example? 

### ISSUE THREAD

**Issue by jackcarlisle** [dwyl/learn-aws-lambda#8]

**Comment by jackcarlisle** [comment]
<img width="937" alt="screen shot 2016-01-24 at 15 11 27" src="https://cloud.githubusercontent.com/assets/12450298/12537249/181e2fac-c2b2-11e5-9363-68d7505c4651.png">

**Comment by jackcarlisle** [comment]
<img width="661" alt="screen shot 2016-01-24 at 12 38 05" src="https://cloud.githubusercontent.com/assets/12450298/12537265/9fc520dc-c2b2-11e5-88df-cf53dccb59dd.png">

**Comment by jackcarlisle** [comment]
<img width="613" alt="screen shot 2016-01-24 at 15 55 13" src="https://cloud.githubusercontent.com/assets/12450298/12537272/dd7a7120-c2b2-11e5-84d9-40a10a3d2ef0.png">

**Comment by jackcarlisle** [comment]
<img width="934" alt="screen shot 2016-01-24 at 16 20 38" src="https://cloud.githubusercontent.com/assets/12450298/12537413/7374470c-c2b6-11e5-8e3a-9baaa99c06aa.png">

**Comment by jackcarlisle** [comment]
<img width="925" alt="screen shot 2016-01-24 at 16 27 43" src="https://cloud.githubusercontent.com/assets/12450298/12537454/acee35b4-c2b7-11e5-99ba-3304394f3d18.png">

**Comment by jackcarlisle** [comment]
<img width="1655" alt="screen shot 2016-01-24 at 16 36 11" src="https://cloud.githubusercontent.com/assets/12450298/12537495/94d2171a-c2b8-11e5-861e-9225d3b17f28.png">

**Comment by nelsonic** [comment]
this is the _manual_ way of uploading a `.zip` file containing our Lambda Function.
_next_ we need to add an example of uploading a `.zip` to S3 and enable it as a Lambda. see: #23
